/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestIndexRouteImport } from './routes/invest.index'
import { Route as InvestSlugRouteImport } from './routes/invest.$slug'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestIndexRoute = InvestIndexRouteImport.update({
  id: '/invest/',
  path: '/invest/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestSlugRoute = InvestSlugRouteImport.update({
  id: '/invest/$slug',
  path: '/invest/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/vehicles': typeof VehiclesRoute
  '/invest/$slug': typeof InvestSlugRoute
  '/invest/': typeof InvestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/vehicles': typeof VehiclesRoute
  '/invest/$slug': typeof InvestSlugRoute
  '/invest': typeof InvestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/vehicles': typeof VehiclesRoute
  '/invest/$slug': typeof InvestSlugRoute
  '/invest/': typeof InvestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/vehicles' | '/invest/$slug' | '/invest/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/vehicles' | '/invest/$slug' | '/invest'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/vehicles'
    | '/invest/$slug'
    | '/invest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  VehiclesRoute: typeof VehiclesRoute
  InvestSlugRoute: typeof InvestSlugRoute
  InvestIndexRoute: typeof InvestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/': {
      id: '/invest/'
      path: '/invest'
      fullPath: '/invest/'
      preLoaderRoute: typeof InvestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/$slug': {
      id: '/invest/$slug'
      path: '/invest/$slug'
      fullPath: '/invest/$slug'
      preLoaderRoute: typeof InvestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  VehiclesRoute: VehiclesRoute,
  InvestSlugRoute: InvestSlugRoute,
  InvestIndexRoute: InvestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
